server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: hhtp://localhost:8761/eureka
    instance:
      hostnmae: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        routes:
          - id: usuario-service
            uri: lb://usuario-service
            predicates:
              - Path=/usuario/**
          - id: auto-service
            uri: lb://Auto-service
            predicates:
              - Path=/Auto/**
          - id: moto-service
            uri: lb://Moto-service
            predicates:
              - Path=/Moto/**